#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

# Return codes
#
# Further information on WildlifeSystems standard reurn codes can be found
# at https://docs.wildlife.systems/return-codes.html
# 0 - Success
# 40 - Unsupported device

case "$1" in
        list)
                echo "none           None"
                echo "rpi-cam        Raspberry Pi Camera"
                echo "rpi-noir       Raspberry Pi NoIR Camera"
                ;;
        rpi-cam|rpi-noir)
                sudo raspi-config nonint do_camera 0
                ;;
        none)
                sudo raspi-config nonint do_camera 1
                ;;
        *)
                echo "$1 is not supported."
                exit 40
                ;;
esac
