#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

wget https://github.com/Wildlife-Systems/image-device-control/raw/master/idc-inst
chown root:root idc-inst
chmod +x idc-inst
mv idc-inst /usr/bin
